import RPi.GPIO as GPIO
import time

GPIO.setwarnings(False)

GPIO.setmode(GPIO.BOARD)

GPIO.setup(12, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)

a = 0.01

for x in range(30):
	GPIO.output(12, GPIO.LOW)
	GPIO.output(16, GPIO.LOW)
	GPIO.output(18, GPIO.LOW)
	GPIO.output(22, GPIO.LOW)
	time.sleep(a)
	GPIO.output(12, GPIO.HIGH)
	time.sleep(a)
	GPIO.output(12, GPIO.LOW)
	time.sleep(a)
	GPIO.output(16, GPIO.HIGH)
	time.sleep(a)
	GPIO.output(16, GPIO.LOW)
	time.sleep(a)
	GPIO.output(18, GPIO.HIGH)
	time.sleep(a)
	GPIO.output(18, GPIO.LOW)
	time.sleep(a)
	GPIO.output(22, GPIO.HIGH)
	time.sleep(a)
	GPIO.output(22, GPIO.LOW)
	time.sleep(a)
	GPIO.output(22, GPIO.HIGH)
	time.sleep(a)
	GPIO.output(22, GPIO.LOW)
	time.sleep(a)
	GPIO.output(18, GPIO.HIGH)
	time.sleep(a)
	GPIO.output(18, GPIO.LOW)
	time.sleep(a)
	GPIO.output(16, GPIO.HIGH)
	time.sleep(a)
	GPIO.output(16, GPIO.LOW)
	time.sleep(a)
	GPIO.output(12, GPIO.HIGH)
	time.sleep(a)
	GPIO.output(12, GPIO.LOW)
